language: php

php:
    - 7.0
    - 7.1

before_script:
    - phpenv config-rm xdebug.ini
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction --prefer-source

script: vendor/bin/phpspec run
