language: php

php:
    - 7.1
    - 7.2

before_script:
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction --prefer-source

script:
    - vendor/bin/phpspec run

after_success:
    - travis_retry php vendor/bin/php-coveralls
